## HW 1

In [77]:
import numpy as np

## Point 1 

In [78]:
a1 = np.array(range (1, 11))
print(a1)

[ 1  2  3  4  5  6  7  8  9 10]


## Point 2

In [79]:
a2 = np.zeros((3, 3), dtype=int)
print(a2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


## Point 3

In [80]:
a3 = np.random.randint(1, 11, size=(5, 5))
print(a3)


[[ 5  8  7  1  4]
 [ 4  9  7  3  2]
 [ 3  5  5  9  2]
 [ 2  8 10  5  8]
 [ 2 10  9  3  1]]


## Point 4

In [81]:
a4 = np.random.rand(4, 4)
print(a4)


[[0.6060918  0.22626895 0.66625254 0.8078977 ]
 [0.96529603 0.59816587 0.90312365 0.68593189]
 [0.21015016 0.12294786 0.35328551 0.24545597]
 [0.41450902 0.62556586 0.71239824 0.37675312]]


## Point 5

In [82]:
b1 = np.random.randint(1, 11, size=5)
b2 = np.random.randint(1, 11, size=5)

print("Масив 1:", b1)
print("Масив 2:", b2)

sum = b1+b2
difference  = b1-b2
produkt = b1*b2

print("Додавання:", sum)
print("Віднімання:", difference)
print("Множення:", produkt)


Масив 1: [6 2 4 8 1]
Масив 2: [7 9 1 2 2]
Додавання: [13 11  5 10  3]
Віднімання: [-1 -7  3  6 -1]
Множення: [42 18  4 16  2]


## Point 6

In [83]:

c1 = np.random.rand(7)
c2 = np.random.rand(7)

print("Вектор 1:", c1)
print("Вектор 2:", c2)

product = np.dot(c1, c2)

print("Скалярний добуток:", product)


Вектор 1: [0.38051337 0.54651242 0.31560614 0.42566103 0.1517884  0.65912847
 0.50795597]
Вектор 2: [0.45800324 0.13692948 0.07324264 0.82555857 0.16368247 0.50875212
 0.42208198]
Скалярний добуток: 1.1982111273169558


## Point 7

In [84]:
import numpy as np

d1 = np.random.randint(1, 11, size=(2, 2))
d2 = np.random.randint(1, 11, size=(2, 3))

print("Матриця 1:\n", d1)
print("Матриця 2:\n", d2)

product = np.dot(d1, d2)

print("Результат перемноження:\n", product)


Матриця 1:
 [[ 3  9]
 [10  6]]
Матриця 2:
 [[ 6  9 10]
 [ 7  7  6]]
Результат перемноження:
 [[ 81  90  84]
 [102 132 136]]


## Point 8

In [85]:
a8 = np.random.randint(1, 11, size=(3, 3))

print("Матриця:\n", a8)

try:
    inverse_matrix = np.linalg.inv(a8)
    print("Обернена матриця:\n", inverse_matrix)
except np.linalg.LinAlgError:
    print("Матриця не є оборотною.")


Матриця:
 [[10  6  6]
 [ 2  2  2]
 [ 5  6 10]]
Обернена матриця:
 [[ 0.25   -0.75    0.    ]
 [-0.3125  2.1875 -0.25  ]
 [ 0.0625 -0.9375  0.25  ]]


## Point 9

In [86]:
a9 = np.random.rand(4, 4)

print("Початкова матриця:\n", a9)

transposed_matrix = a9.T

print("Транспонована матриця:\n", transposed_matrix)


Початкова матриця:
 [[0.90582387 0.45342318 0.57614958 0.96416644]
 [0.7523458  0.76393034 0.92789727 0.24468482]
 [0.17330692 0.228164   0.61502643 0.28050029]
 [0.96521284 0.54336612 0.78051681 0.32570012]]
Транспонована матриця:
 [[0.90582387 0.7523458  0.17330692 0.96521284]
 [0.45342318 0.76393034 0.228164   0.54336612]
 [0.57614958 0.92789727 0.61502643 0.78051681]
 [0.96416644 0.24468482 0.28050029 0.32570012]]


## Point 10

In [87]:

a10 = np.random.randint(1, 11, size=(3, 4))
v = np.random.randint(1, 11, size=4)

print("Матриця:\n", a10)
print("Вектор:\n", v)

result = np.dot(a10, v)

print("Результат перемноження:\n", result)


Матриця:
 [[ 5 10  1  5]
 [ 4  2  8  2]
 [ 7  5  9  5]]
Вектор:
 [4 5 5 6]
Результат перемноження:
 [105  78 128]


## Point 11

In [88]:
a11 = np.random.rand(2, 3)
v2 = np.random.rand(3)

print("Матриця:\n", a11)
print("Вектор:\n", v2)

result = np.dot(a11, v2)

print("Результат перемноження:\n", result)


Матриця:
 [[0.86673772 0.83064603 0.22531285]
 [0.31039385 0.51882173 0.19523689]]
Вектор:
 [0.80982842 0.02278786 0.67100583]
Результат перемноження:
 [0.87202372 0.39419369]


## Point 12

In [89]:
e1 = np.random.randint(1, 11, size=(2, 2))
e2 = np.random.randint(1, 11, size=(2, 2))

print("Матриця 1:\n", e1)
print("Матриця 2:\n", e2)

print("Результат поелементного множення:\n", e1*e2)


Матриця 1:
 [[8 2]
 [1 5]]
Матриця 2:
 [[ 8  5]
 [10 10]]
Результат поелементного множення:
 [[64 10]
 [10 50]]


## Point 13

In [90]:
f1 = np.random.randint(1, 11, size=(2, 2))
f2 = np.random.randint(1, 11, size=(2, 2))

print("Матриця 1:\n", f1)
print("Матриця 2:\n", f2)

product13 = np.dot(f1, f2)

print("Добуток:\n", product13)

Матриця 1:
 [[ 4  5]
 [ 1 10]]
Матриця 2:
 [[ 4  9]
 [ 9 10]]
Добуток:
 [[ 61  86]
 [ 94 109]]


## Point 14

In [91]:
a14 = np.random.randint(1, 101, size=(5, 5))

print("Матриця:\n", a14)

print("Сума елементів матриці:", a14.sum())


Матриця:
 [[82 78 21 75 31]
 [78  3 95 37  2]
 [84 90 38 33 96]
 [41 25 66 82 58]
 [12 64 46  3 34]]
Сума елементів матриці: 1274


## Point 15

In [92]:
g1 = np.random.randint(1, 11, size=(4, 4))
g2 = np.random.randint(1, 11, size=(4, 4))

print("Матриця 1:\n", g1)
print("Матриця 2:\n", g2)

print("Різниця матриць:\n", g1-g2)

Матриця 1:
 [[1 6 3 8]
 [7 3 7 2]
 [8 5 9 1]
 [7 3 2 3]]
Матриця 2:
 [[ 2  9  5  8]
 [ 7 10  5  3]
 [ 6  1  4  8]
 [ 9  1  3  3]]
Різниця матриць:
 [[-1 -3 -2  0]
 [ 0 -7  2 -1]
 [ 2  4  5 -7]
 [-2  2 -1  0]]


## Point 16

In [93]:
a16 = np.random.rand(3, 3)

print("Матриця:\n", a16)

sum_vec = np.sum(a16, axis=1, keepdims=True)

print("Вектор-стовпчик із сумою елементів кожного рядка:\n", sum_vec)


Матриця:
 [[0.40084245 0.7959949  0.65709441]
 [0.31170817 0.94811089 0.2153782 ]
 [0.14691562 0.44654986 0.62572124]]
Вектор-стовпчик із сумою елементів кожного рядка:
 [[1.85393176]
 [1.47519727]
 [1.21918672]]


## Point 17

In [94]:

a17 = np.random.randint(1, 11, size=(3, 4))

print("Початкова матриця:\n", a17)

squared = np.square(a17)

print("Матриця з квадратами чисел:\n", squared)
print("Матриця з квадратами чисел:\n", a17**2)


Початкова матриця:
 [[10  9  4 10]
 [10  9 10  2]
 [ 5 10  3  5]]
Матриця з квадратами чисел:
 [[100  81  16 100]
 [100  81 100   4]
 [ 25 100   9  25]]
Матриця з квадратами чисел:
 [[100  81  16 100]
 [100  81 100   4]
 [ 25 100   9  25]]


## Point 18

In [95]:
v18 = np.random.randint(1, 51, size=4)

print("Початковий вектор:\n", v18)

print("Вектор з квадратними коренями чисел:\n", np.sqrt(v18))


Початковий вектор:
 [ 6  2  1 19]
Вектор з квадратними коренями чисел:
 [2.44948974 1.41421356 1.         4.35889894]
